### PR TITLE
docs : Updated mindsdb installation docs

### PR DESCRIPTION
**Pull request by yash2189**
Fixes #861 of mindsdb issues

## Please describe what changes you made in as much detail as possible
  - Changes have been made under `mindsdb-docs/docs/Installing.md`
  - Previously, there was a section for `Install on Windows using MindsDB installers`. The old file can be found [here](https://github.com/mindsdb/mindsdb-docs/blob/master/mindsdb-docs/docs/Installing.md#install-using-virtual-environment)
  - This section has been removed . Updated file [here](https://github.com/yash2189/mindsdb-docs/blob/fix%23861/mindsdb-docs/docs/Installing.md)

### CODE REVIEW

**Comment by yash2189** [comment]
@ZoranPandovski Please review my PR #107  under mindsdb issue #861

**Review by ZoranPandovski — CHANGES_REQUESTED** [review]
Instead of removing the section, we need that one to be added before the  Install using virtual environment

**Comment by yash2189** [comment]
@ZoranPandovski Please review the changes.
Thanks.

**Review by ZoranPandovski — APPROVED** [review]
Thanks

**Pull request merged**
