### PR TITLE
Fixed Display of SQL Query in the docs

### PR DESCRIPTION
**Pull request by yash2189**
Fixes #857 from mindsdb issues

## Please describe what changes you made in as much detail as possible
  - Changes have been made under `mindsdb-docs/docs/databases/tutorials/AiTablesInPostgreSQL.md`
  - Previously, the PostgreSQL code was not properly formatted. This the [previous](https://github.com/yash2189/mindsdb-docs/blob/master/mindsdb-docs/docs/databases/tutorials/AiTablesInPostgreSQL.md) file.
  - Added a `sql` block for the same , find the new file [here](https://github.com/yash2189/mindsdb-docs/blob/fix%23857/mindsdb-docs/docs/databases/tutorials/AiTablesInPostgreSQL.md)

### CODE REVIEW

**Comment by yash2189** [comment]
@ZoranPandovski Please review my PR for the issue #857 of mindsdb

**Review by ZoranPandovski — CHANGES_REQUESTED** [review]
Are you sure this will display correctly? I think you need 3 ```

**Comment by yash2189** [comment]
@ZoranPandovski in the file the changes are being displayed properly. I'll change it to ```

**Comment by yash2189** [comment]
@ZoranPandovski Can you please check the changes?

**Review by ZoranPandovski — APPROVED** [review]
Thanks

**Pull request merged**
